; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
lib_deps = https://github.com/olikraus/U8g2_Arduino.git
           coryjfowler/mcp_can@^1.5.1
build_flags = -finput-charset=UTF-8 -fexec-charset=UTF-8